development:
  bin_path: "/usr/bin"
  searchd_binary_name: searchd
  indexer_binary_name: indexer
  port: 9312
production:
  bin_path: "/usr/bin"
  searchd_binary_name: searchd
  indexer_binary_name: indexer
  port: 9312
test:
  bin_path: "/usr/bin"
  searchd_binary_name: searchd
  indexer_binary_name: indexer
  port: 9313